server:
  port: 8762
spring:
  application:
    name: zuul-server
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:~/h2/testdb
    driver-class-name: org.h2.Driver
    username: username
    password: password
    hikari:
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 180000
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: foo

zuul:
  prefix: /api
  routes:
    account:
      path: /account/**
      serviceId: account-service
    customer:
      path: /customer/**
      serviceId: customer-service

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.2.1:8761/eureka/
    registerWithEureka: false


management:
  endpoints:
    web:
      exposure:
        include: "*"

swagger:
  title: SWAGGER-title
  desc: SWAGGER-desc
  version: 1.0.0
  license: SWAGGER-license
  license-url: SWAGGER-licenseurl
  contact:
    name: contact-name
    url: contact-url
    email: contact-email


